"use client";

import { useState, useEffect, useCallback } from "react";
import TopNav from "@/components/TopNav";
import { useLanguage } from "@/components/LanguageContext";
import Link from "next/link";

// ============================================
// CUSTODY STATEMENTS
// Real data from /api/admin/statements (public endpoint)
// ============================================

interface StatementContent {
  tr: string;
  en: string;
  de?: string;
  fr?: string;
  ar?: string;
  ru?: string;
}

interface Statement {
  id: string;
  type: "monthly" | "quarterly" | "annual";
  title: StatementContent;
  period: StatementContent;
  periodEnding: string;
  generatedDate: string;
  fileSize: string;
  status: "available" | "generating" | "scheduled";
  published: boolean;
  pdfUrl?: string;
}

const translations: Record<string, Record<string, string>> = {
  tr: {
    title: "Saklama Bildirimleri",
    subtitle: "Bağımsız saklama beyanları",
    bannerTitle: "Bağımsız Saklama Beyanı",
    bannerDesc: "Tüm beyanlar bağımsız saklama sağlayıcısı tarafından oluşturulmaktadır",
    custodian: "Saklama",
    auditedBy: "Denetleyen",
    jurisdiction: "Yetki Alanı",
    all: "Tümü",
    monthly: "Aylık",
    quarterly: "Çeyreklik",
    annual: "Yıllık",
    periodEnding: "Dönem Sonu",
    generated: "Oluşturulma",
    fileSize: "Dosya Boyutu",
    downloadPdf: "PDF İndir",
    preview: "Önizleme",
    generating: "Oluşturuluyor",
    scheduled: "Planlandı",
    requestCustom: "Özel Beyan Talep Et",
    requestCustomDesc: "Belirli bir dönem için özelleştirilmiş beyan talep edin",
    back: "Geri",
    loading: "Raporlar yükleniyor...",
    noStatements: "Henüz yayınlanmış rapor yok",
    errorLoading: "Raporlar yüklenemedi",
    retry: "Tekrar Dene",
  },
  en: {
    title: "Custody Statements",
    subtitle: "Independent custody statements",
    bannerTitle: "Independent Custody Statement",
    bannerDesc: "All statements are generated by the independent custody provider",
    custodian: "Custodian",
    auditedBy: "Audited by",
    jurisdiction: "Jurisdiction",
    all: "All",
    monthly: "Monthly",
    quarterly: "Quarterly",
    annual: "Annual",
    periodEnding: "Period Ending",
    generated: "Generated",
    fileSize: "File Size",
    downloadPdf: "Download PDF",
    preview: "Preview",
    generating: "Generating",
    scheduled: "Scheduled",
    requestCustom: "Request Custom Statement",
    requestCustomDesc: "Request a customized statement for a specific period",
    back: "Back",
    loading: "Loading statements...",
    noStatements: "No published statements yet",
    errorLoading: "Failed to load statements",
    retry: "Retry",
  },
  de: {
    title: "Verwahrungsauszüge",
    subtitle: "Unabhängige Verwahrungsauszüge",
    bannerTitle: "Unabhängiger Verwahrungsauszug",
    bannerDesc: "Alle Auszüge werden vom unabhängigen Verwahrer erstellt",
    custodian: "Verwahrer",
    auditedBy: "Geprüft von",
    jurisdiction: "Gerichtsbarkeit",
    all: "Alle",
    monthly: "Monatlich",
    quarterly: "Vierteljährlich",
    annual: "Jährlich",
    periodEnding: "Periodenende",
    generated: "Erstellt am",
    fileSize: "Dateigröße",
    downloadPdf: "PDF herunterladen",
    preview: "Vorschau",
    generating: "Wird erstellt",
    scheduled: "Geplant",
    requestCustom: "Benutzerdefinierten Auszug anfordern",
    requestCustomDesc: "Fordern Sie einen maßgeschneiderten Auszug für einen bestimmten Zeitraum an",
    back: "Zurück",
    loading: "Auszüge werden geladen...",
    noStatements: "Noch keine veröffentlichten Auszüge",
    errorLoading: "Auszüge konnten nicht geladen werden",
    retry: "Erneut versuchen",
  },
  fr: {
    title: "Relevés de conservation",
    subtitle: "Relevés de conservation indépendants",
    bannerTitle: "Relevé de conservation indépendant",
    bannerDesc: "Tous les relevés sont générés par le prestataire de conservation indépendant",
    custodian: "Dépositaire",
    auditedBy: "Audité par",
    jurisdiction: "Juridiction",
    all: "Tous",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    annual: "Annuel",
    periodEnding: "Fin de période",
    generated: "Généré le",
    fileSize: "Taille du fichier",
    downloadPdf: "Télécharger PDF",
    preview: "Aperçu",
    generating: "En cours de génération",
    scheduled: "Programmé",
    requestCustom: "Demander un relevé personnalisé",
    requestCustomDesc: "Demandez un relevé personnalisé pour une période spécifique",
    back: "Retour",
    loading: "Chargement des relevés...",
    noStatements: "Aucun relevé publié pour le moment",
    errorLoading: "Impossible de charger les relevés",
    retry: "Réessayer",
  },
  ar: {
    title: "كشوفات الحفظ",
    subtitle: "كشوفات حفظ مستقلة",
    bannerTitle: "كشف حفظ مستقل",
    bannerDesc: "جميع الكشوفات يتم إنشاؤها من قبل مزود الحفظ المستقل",
    custodian: "الحافظ",
    auditedBy: "مدقق من قبل",
    jurisdiction: "الولاية القضائية",
    all: "الكل",
    monthly: "شهري",
    quarterly: "ربع سنوي",
    annual: "سنوي",
    periodEnding: "نهاية الفترة",
    generated: "تاريخ الإنشاء",
    fileSize: "حجم الملف",
    downloadPdf: "تحميل PDF",
    preview: "معاينة",
    generating: "جاري الإنشاء",
    scheduled: "مجدول",
    requestCustom: "طلب كشف مخصص",
    requestCustomDesc: "اطلب كشفًا مخصصًا لفترة محددة",
    back: "رجوع",
    loading: "جاري تحميل الكشوفات...",
    noStatements: "لا توجد كشوفات منشورة بعد",
    errorLoading: "فشل تحميل الكشوفات",
    retry: "إعادة المحاولة",
  },
  ru: {
    title: "Выписки хранения",
    subtitle: "Независимые выписки хранения",
    bannerTitle: "Независимая выписка хранения",
    bannerDesc: "Все выписки формируются независимым хранителем",
    custodian: "Хранитель",
    auditedBy: "Аудитор",
    jurisdiction: "Юрисдикция",
    all: "Все",
    monthly: "Ежемесячные",
    quarterly: "Ежеквартальные",
    annual: "Годовые",
    periodEnding: "Конец периода",
    generated: "Дата создания",
    fileSize: "Размер файла",
    downloadPdf: "Скачать PDF",
    preview: "Предпросмотр",
    generating: "Формируется",
    scheduled: "Запланировано",
    requestCustom: "Запросить индивидуальную выписку",
    requestCustomDesc: "Запросите выписку за определённый период",
    back: "Назад",
    loading: "Загрузка выписок...",
    noStatements: "Опубликованных выписок пока нет",
    errorLoading: "Не удалось загрузить выписки",
    retry: "Повторить",
  },
};

const typeConfig: Record<string, { color: string; bgColor: string; icon: string }> = {
  monthly: { color: "#BFA181", bgColor: "bg-[#BFA181]/15", icon: "📅" },
  quarterly: { color: "#3b82f6", bgColor: "bg-blue-500/15", icon: "🏅" },
  annual: { color: "#8b5cf6", bgColor: "bg-purple-500/15", icon: "📊" },
};

export default function StatementsPage() {
  const { lang } = useLanguage();
  const t = translations[lang] || translations.en;

  const [activeFilter, setActiveFilter] = useState("all");
  const [statements, setStatements] = useState<Statement[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  // Fetch published statements from API
  const fetchStatements = useCallback(async () => {
    setLoading(true);
    setError(false);
    try {
      const res = await fetch("/api/admin/statements");
      const data = await res.json();
      if (data.success && Array.isArray(data.statements)) {
        setStatements(data.statements);
      } else {
        setStatements([]);
      }
    } catch (err) {
      console.error("Failed to fetch statements:", err);
      setError(true);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchStatements();
  }, [fetchStatements]);

  const filteredStatements = activeFilter === "all"
    ? statements
    : statements.filter(s => s.type === activeFilter);

  const filters = [
    { key: "all", label: t.all },
    { key: "monthly", label: t.monthly },
    { key: "quarterly", label: t.quarterly },
    { key: "annual", label: t.annual },
  ];

  // Get localized text from StatementContent
  const getText = (content: StatementContent | string | undefined): string => {
    if (!content) return "";
    if (typeof content === "string") return content;
    return content[lang as keyof StatementContent] || content.en || content.tr || "";
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr || dateStr === "—") return dateStr;
    try {
      return new Date(dateStr).toLocaleDateString(
        lang === "tr" ? "tr-TR" : lang === "de" ? "de-DE" : lang === "fr" ? "fr-FR" : lang === "ar" ? "ar-SA" : lang === "ru" ? "ru-RU" : "en-US",
        { year: "numeric", month: "short", day: "numeric" }
      );
    } catch {
      return dateStr;
    }
  };

  return (
    <div className="min-h-screen bg-[#f8f5f0] dark:bg-[#0a0a0a]">
      <TopNav />
      <div className="max-w-3xl mx-auto px-4 py-6">
        {/* Header */}
        <div className="flex items-center gap-4 mb-6">
          <Link href="/client-center" className="p-2 rounded-lg hover:bg-black/5 dark:hover:bg-white/5 transition">
            <svg className="w-5 h-5 text-slate-800 dark:text-white" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" /></svg>
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-slate-800 dark:text-white">{t.title}</h1>
            <p className="text-sm text-slate-500 dark:text-zinc-400">{t.subtitle}</p>
          </div>
        </div>

        {/* Institutional Banner */}
        <div className="flex items-start gap-3 p-4 rounded-xl bg-[#BFA181]/10 border border-[#BFA181]/30 mb-4">
          <div className="w-10 h-10 rounded-full bg-[#BFA181]/20 flex items-center justify-center flex-shrink-0">
            <svg className="w-5 h-5 text-[#BFA181]" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" /></svg>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-slate-800 dark:text-white">{t.bannerTitle}</h3>
            <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5">{t.bannerDesc}</p>
          </div>
        </div>

        {/* Filter Buttons */}
        <div className="flex gap-2 mb-5">
          {filters.map(f => (
            <button
              key={f.key}
              onClick={() => setActiveFilter(f.key)}
              className={`px-4 py-2 rounded-lg text-xs font-semibold transition ${
                activeFilter === f.key
                  ? "bg-[#BFA181] text-white"
                  : "bg-white dark:bg-zinc-800/50 text-slate-600 dark:text-zinc-400 border border-stone-200 dark:border-zinc-700/50 hover:bg-slate-50 dark:hover:bg-zinc-700/50"
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>

        {/* Loading state */}
        {loading && (
          <div className="bg-white dark:bg-zinc-800/50 rounded-xl border border-stone-200 dark:border-zinc-700/50 p-12 text-center">
            <div className="w-8 h-8 border-2 border-[#BFA181] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
            <p className="text-slate-500 dark:text-zinc-400 text-sm">{t.loading}</p>
          </div>
        )}

        {/* Error state */}
        {!loading && error && (
          <div className="bg-white dark:bg-zinc-800/50 rounded-xl border border-stone-200 dark:border-zinc-700/50 p-12 text-center">
            <p className="text-slate-500 dark:text-zinc-400 text-sm mb-4">{t.errorLoading}</p>
            <button onClick={fetchStatements} className="px-4 py-2 text-sm font-medium text-white bg-[#BFA181] rounded-lg hover:bg-[#a88e6e] transition-colors">
              {t.retry}
            </button>
          </div>
        )}

        {/* Empty state */}
        {!loading && !error && filteredStatements.length === 0 && (
          <div className="bg-white dark:bg-zinc-800/50 rounded-xl border border-stone-200 dark:border-zinc-700/50 p-12 text-center">
            <svg className="w-16 h-16 text-slate-300 dark:text-zinc-600 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <p className="text-slate-500 dark:text-zinc-400 text-sm">{t.noStatements}</p>
          </div>
        )}

        {/* Statement Cards */}
        {!loading && !error && filteredStatements.length > 0 && (
          <div className="space-y-3">
            {filteredStatements.map(statement => {
              const config = typeConfig[statement.type] || typeConfig.monthly;
              return (
                <div key={statement.id} className="bg-white dark:bg-zinc-800/50 rounded-xl border border-stone-200 dark:border-zinc-700/50 p-4">
                  <div className="flex items-start gap-3 mb-3">
                    <div className={`w-10 h-10 rounded-full ${config.bgColor} flex items-center justify-center flex-shrink-0`}>
                      <span className="text-lg">{config.icon}</span>
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <h3 className="text-sm font-semibold text-slate-800 dark:text-white">{getText(statement.title)}</h3>
                        <span className="px-2 py-0.5 rounded text-[10px] font-semibold" style={{ backgroundColor: config.color + "20", color: config.color }}>
                          {t[statement.type]}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Details */}
                  <div className="grid grid-cols-3 gap-2 mb-3 pl-[52px]">
                    <div>
                      <p className="text-[10px] text-slate-400 dark:text-zinc-500">{t.periodEnding}</p>
                      <p className="text-xs text-slate-700 dark:text-zinc-300 font-medium">{formatDate(statement.periodEnding)}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 dark:text-zinc-500">{t.generated}</p>
                      <p className="text-xs text-slate-700 dark:text-zinc-300 font-medium">{formatDate(statement.generatedDate)}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 dark:text-zinc-500">{t.fileSize}</p>
                      <p className="text-xs text-slate-700 dark:text-zinc-300 font-medium">{statement.fileSize || "—"}</p>
                    </div>
                  </div>

                  {/* Actions */}
                  {statement.pdfUrl ? (
                    <div className="flex gap-2 pl-[52px]">
                      <button
                        onClick={() => window.open(statement.pdfUrl, "_blank")}
                        className="flex-1 py-2.5 rounded-lg text-xs font-semibold text-white transition hover:opacity-90"
                        style={{ backgroundColor: config.color }}
                      >
                        {t.downloadPdf}
                      </button>
                      <button
                        onClick={() => window.open(statement.pdfUrl, "_blank")}
                        className="px-4 py-2.5 rounded-lg text-xs font-semibold border border-stone-200 dark:border-zinc-700 text-slate-600 dark:text-zinc-400 hover:bg-slate-50 dark:hover:bg-zinc-700/50 transition"
                      >
                        {t.preview}
                      </button>
                    </div>
                  ) : (
                    <div className="pl-[52px]">
                      <span className="text-xs text-slate-400 dark:text-zinc-500 italic">PDF —</span>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}

        {/* Request Custom Statement */}
        <div className="mt-4 mb-8 border-2 border-dashed border-stone-300 dark:border-zinc-600 rounded-xl p-4 flex items-center gap-3 cursor-pointer hover:border-[#BFA181] hover:bg-[#BFA181]/5 transition">
          <div className="w-10 h-10 rounded-full bg-[#BFA181]/15 flex items-center justify-center">
            <svg className="w-5 h-5 text-[#BFA181]" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" /></svg>
          </div>
          <div className="flex-1">
            <p className="text-sm font-semibold text-slate-800 dark:text-white">{t.requestCustom}</p>
            <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5">{t.requestCustomDesc}</p>
          </div>
          <svg className="w-5 h-5 text-slate-400 dark:text-zinc-500" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" /></svg>
        </div>
      </div>
    </div>
  );
}
